version: "3"
services:
  gobudgetdb:
    container_name: gobudgetdb
    image: postgres
    environment:
      POSTGRES_PASSWORD: gobudget
      POSTGRES_USER: gobudget
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  gobudgetdbadmin:
    container_name: gobudgetdbadmin
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: gobudget@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: gobudget
    ports:
      - "5051:80"
    depends_on:
      - gobudgetdb
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
      - ./volumes/config_local.py:/pgadmin
  gobudgetdredis:
    container_name: gobudgetdredis
    image: redis:alpine
    ports:
      - "6380:6379"
